class Session:

    def __init__(self, title, subject, school, maxSize, date):
        self.__title = title #string - generated by user
        self.__subject = subject #int - from drop down of presets
        self.__school = school #string? - also from dropdown?
        self.__maxSize = maxSize #int - input by user (maybe -1 if no max?)
        self.__date = date #date? - date of event chosen by user

        self.__userList = [] #list of user objects belonging to this session
        self.__currentSize = 0 #size of userList

        self.__searchTerms = [self.__subject, self.__maxSize, self.__date]

    @property
    def searchTerms(self):
        return self.__searchTerms

    @property  
    def subject(self):
        return self.__subject
    
    @property
    def maxSize(self):
        return self.__maxSize
    
    @property
    def school(self):
        return self.__school
    
    @property
    def title(self):
        return self.__title

    @property
    def date(self):
        return self.__date
    
    def match(self):
        pass


#end class stuff
'''def main():
    pass

if __name__ == "__main__":
    main()'''
